version: "3.7"

services:
  apm-steam-web-dev:
    build:
      context: ../
      dockerfile: Dockerfile-dev
    environment:
      NODE_ENV: development
    healthcheck:
      test: curl --fail http://localhost || exit 1
      interval: 10s
      timeout: 2s
      retries: 3
      start_period: 60s
    deploy:
      mode: global
      resources:
        limits:
          cpus: "0.8"
          memory: "900MB"
      update_config:
        parallelism: 2
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - 8081:80
    labels:
      - "apm-steam-web-dev-apps"
